# Terraform Variables for op
# Generated by OptiMon on 2025-11-04 19:29:39

environment   = "staging"
project_name  = "op"
aws_region    = "us-east-1"
key_pair_name = "my-key-pair"  # Replace with your key pair name
