# Variables for op
# Generated by OptiMon on 2025-11-04 19:29:39

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "staging"
}

variable "project_name" {
  description = "Project name"  
  type        = string
  default     = "op"
}
