global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'optimon@localhost'
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  # Configuración de email (comentada por defecto)
  # - name: 'email-notifications'
  #   email_configs:
  #     - to: 'admin@empresa.com'
  #       subject: 'OptiMon Alert: {{ .GroupLabels.alertname }}'
  #       body: |
  #         {{ range .Alerts }}
  #         Alert: {{ .Annotations.summary }}
  #         Description: {{ .Annotations.description }}
  #         {{ end }}

  # Configuración de Slack (comentada por defecto)
  # - name: 'slack-notifications'
  #   slack_configs:
  #     - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
  #       channel: '#monitoring'
  #       title: 'OptiMon Alert'
  #       text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']