global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'wacry77@gmail.com'
  smtp_auth_username: 'wacry77@gmail.com'
  smtp_auth_password: 'ygnc fdkn btvh bzii'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'optimon_alerts'

receivers:
- name: 'optimon_alerts'
  email_configs:
  - to: 'wacry77@gmail.com'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']