# Terraform Variables for optimon-azure-demo
# Generated by OptiMon on 2025-11-04 19:24:58

environment   = "staging"
project_name  = "optimon-azure-demo"
location       = "East US"
subscription_id = "your-subscription-id"  # Replace with your subscription ID
ssh_public_key  = "your-ssh-public-key"   # Replace with your SSH public key
