# Variables for optimon-azure-demo
# Generated by OptiMon on 2025-11-04 19:24:58

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "staging"
}

variable "project_name" {
  description = "Project name"  
  type        = string
  default     = "optimon-azure-demo"
}
