groups:
  - name: optimon_windows_alerts
    rules:
      - alert: HighCPUUsage_Windows
        expr: 100 - (avg(rate(windows_cpu_time_total{instance="host.docker.internal:9182",mode="idle"}[2m])) * 100) > 85
        for: 2m
        labels:
          severity: warning
          server_type: windows
          server_name: "PC-Local-Windows"
        annotations:
          summary: "High CPU usage on Windows server"
          description: "CPU usage is {{ $value }}% for more than 2 minutes on Windows server"

      - alert: HighMemoryUsage_Windows
        expr: ((windows_cs_physical_memory_bytes{instance="host.docker.internal:9182"} - windows_os_physical_memory_free_bytes{instance="host.docker.internal:9182"}) / windows_cs_physical_memory_bytes{instance="host.docker.internal:9182"}) * 100 > 90
        for: 5m
        labels:
          severity: critical
          server_type: windows
          server_name: "PC-Local-Windows"
        annotations:
          summary: "High memory usage on Windows server"
          description: "Memory usage is {{ $value }}% for more than 5 minutes on Windows server"

      - alert: DiskSpaceLow_Windows
        expr: ((windows_logical_disk_size_bytes{instance="host.docker.internal:9182"} - windows_logical_disk_free_bytes{instance="host.docker.internal:9182"}) / windows_logical_disk_size_bytes{instance="host.docker.internal:9182"}) * 100 > 90
        for: 5m
        labels:
          severity: warning
          server_type: windows
          server_name: "PC-Local-Windows"
        annotations:
          summary: "Low disk space on Windows server"
          description: "Disk {{ $labels.volume }} usage is {{ $value }}% on Windows server"

      - alert: WindowsServerDown
        expr: up{instance="host.docker.internal:9182"} == 0
        for: 1m
        labels:
          severity: critical
          server_type: windows
          server_name: "PC-Local-Windows"
        annotations:
          summary: "Windows server is down"
          description: "Windows server has been down for more than 1 minute"

  - name: optimon_aws_alerts
    rules:
      - alert: HighCPUUsage_AWS
        expr: 100 - (avg(rate(node_cpu_seconds_total{instance="54.83.90.114:9100",mode="idle"}[2m])) * 100) > 85
        for: 2m
        labels:
          severity: warning
          server_type: aws
          server_name: "AWS-EC2-Linux"
        annotations:
          summary: "High CPU usage on AWS EC2"
          description: "CPU usage is {{ $value }}% for more than 2 minutes on AWS EC2 instance"

      - alert: HighMemoryUsage_AWS
        expr: ((node_memory_MemTotal_bytes{instance="54.83.90.114:9100"} - node_memory_MemAvailable_bytes{instance="54.83.90.114:9100"}) / node_memory_MemTotal_bytes{instance="54.83.90.114:9100"}) * 100 > 85
        for: 5m
        labels:
          severity: critical
          server_type: aws
          server_name: "AWS-EC2-Linux"
        annotations:
          summary: "High memory usage on AWS EC2"
          description: "Memory usage is {{ $value }}% for more than 5 minutes on AWS EC2 instance"

      - alert: DiskSpaceLow_AWS
        expr: ((node_filesystem_size_bytes{instance="54.83.90.114:9100",fstype!="tmpfs",mountpoint="/"} - node_filesystem_free_bytes{instance="54.83.90.114:9100",fstype!="tmpfs",mountpoint="/"}) / node_filesystem_size_bytes{instance="54.83.90.114:9100",fstype!="tmpfs",mountpoint="/"}) * 100 > 85
        for: 5m
        labels:
          severity: warning
          server_type: aws
          server_name: "AWS-EC2-Linux"
        annotations:
          summary: "Low disk space on AWS EC2"
          description: "Root disk usage is {{ $value }}% on AWS EC2 instance"

      - alert: HighSystemLoad_AWS
        expr: node_load5{instance="54.83.90.114:9100"} > 2
        for: 5m
        labels:
          severity: warning
          server_type: aws
          server_name: "AWS-EC2-Linux"
        annotations:
          summary: "High system load on AWS EC2"
          description: "System load average is {{ $value }} for more than 5 minutes on AWS EC2"

      - alert: AWSServerDown
        expr: up{instance="54.83.90.114:9100"} == 0
        for: 1m
        labels:
          severity: critical
          server_type: aws
          server_name: "AWS-EC2-Linux"
        annotations:
          summary: "AWS EC2 server is down"
          description: "AWS EC2 instance has been unreachable for more than 1 minute"

  - name: optimon_azure_alerts
    rules:
      - alert: HighCPUUsage_Azure
        expr: 100 - (avg(rate(node_cpu_seconds_total{instance=~"AZURE_VM_IP:9100",mode="idle"}[2m])) * 100) > 85
        for: 2m
        labels:
          severity: warning
          server_type: azure
          server_name: "Azure-VM-Linux"
        annotations:
          summary: "High CPU usage on Azure VM"
          description: "CPU usage is {{ $value }}% for more than 2 minutes on Azure VM"

      - alert: HighMemoryUsage_Azure
        expr: ((node_memory_MemTotal_bytes{instance=~"AZURE_VM_IP:9100"} - node_memory_MemAvailable_bytes{instance=~"AZURE_VM_IP:9100"}) / node_memory_MemTotal_bytes{instance=~"AZURE_VM_IP:9100"}) * 100 > 85
        for: 5m
        labels:
          severity: critical
          server_type: azure
          server_name: "Azure-VM-Linux"
        annotations:
          summary: "High memory usage on Azure VM"
          description: "Memory usage is {{ $value }}% for more than 5 minutes on Azure VM"

      - alert: AzureServerDown
        expr: up{instance=~"AZURE_VM_IP:9100"} == 0
        for: 1m
        labels:
          severity: critical
          server_type: azure
          server_name: "Azure-VM-Linux"
        annotations:
          summary: "Azure VM is down"
          description: "Azure VM has been unreachable for more than 1 minute"

  - name: optimon_linux_physical_alerts
    rules:
      - alert: HighCPUUsage_LinuxPhysical
        expr: 100 - (avg(rate(node_cpu_seconds_total{instance=~"LINUX_PHYSICAL_IP:9100",mode="idle"}[2m])) * 100) > 85
        for: 2m
        labels:
          severity: warning
          server_type: linux_physical
          server_name: "Linux-Physical-Server"
        annotations:
          summary: "High CPU usage on Linux physical server"
          description: "CPU usage is {{ $value }}% for more than 2 minutes on physical Linux server"

      - alert: HighMemoryUsage_LinuxPhysical
        expr: ((node_memory_MemTotal_bytes{instance=~"LINUX_PHYSICAL_IP:9100"} - node_memory_MemAvailable_bytes{instance=~"LINUX_PHYSICAL_IP:9100"}) / node_memory_MemTotal_bytes{instance=~"LINUX_PHYSICAL_IP:9100"}) * 100 > 85
        for: 5m
        labels:
          severity: critical
          server_type: linux_physical
          server_name: "Linux-Physical-Server"
        annotations:
          summary: "High memory usage on Linux physical server"
          description: "Memory usage is {{ $value }}% for more than 5 minutes on physical Linux server"

      - alert: LinuxPhysicalServerDown
        expr: up{instance=~"LINUX_PHYSICAL_IP:9100"} == 0
        for: 1m
        labels:
          severity: critical
          server_type: linux_physical
          server_name: "Linux-Physical-Server"
        annotations:
          summary: "Linux physical server is down"
          description: "Physical Linux server has been unreachable for more than 1 minute"

  - name: optimon_network_alerts
    rules:
      - alert: HighNetworkTraffic_Windows
        expr: rate(windows_net_bytes_received_total{instance="host.docker.internal:9182"}[5m]) > 100000000
        for: 10m
        labels:
          severity: warning
          server_type: windows
          server_name: "PC-Local-Windows"
        annotations:
          summary: "High network traffic on Windows server"
          description: "Network download traffic is {{ $value | humanize }}B/s for more than 10 minutes"

      - alert: HighNetworkTraffic_Linux
        expr: rate(node_network_receive_bytes_total{instance=~"(54.83.90.114:9100|AZURE_VM_IP:9100|LINUX_PHYSICAL_IP:9100)",device!~"lo|docker.*|br.*"}[5m]) > 100000000
        for: 10m
        labels:
          severity: warning
          server_type: linux
        annotations:
          summary: "High network traffic on Linux server"
          description: "Network download traffic is {{ $value | humanize }}B/s on {{ $labels.device }} for more than 10 minutes"