groups:
- name: AlertasGenerales
  rules:
  - alert: AltaCargaCPU
    expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Alta carga de CPU detectada"
      description: "La instancia {{ $labels.instance }} ha superado el 80% de uso de CPU durante más de 5 minutos."

  - alert: InstanciaNoDisponible
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Un exporter de métricas está caído"
      description: "El job '{{ $labels.job }}' en la instancia {{ $labels.instance }} no está respondiendo."
