groups:
- name: AlertasGenerales
  rules:
  # === ALERTAS DE CPU ===
  - alert: AltaCargaCPU
    expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 80
    for: 5m
    labels:
      severity: warning
      component: cpu
    annotations:
      summary: "🚨 Alta carga de CPU detectada"
      description: "La instancia {{ $labels.instance }} ha superado el 80% de uso de CPU durante más de 5 minutos. Valor actual: {{ $value | humanize }}%"

  - alert: CargaCriticaCPU
    expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 95
    for: 2m
    labels:
      severity: critical
      component: cpu
    annotations:
      summary: "🔥 CRÍTICO: CPU al límite"
      description: "La instancia {{ $labels.instance }} tiene un uso de CPU crítico: {{ $value | humanize }}%"

  # === ALERTAS DE MEMORIA ===
  - alert: AltaMemoria
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
    for: 5m
    labels:
      severity: warning
      component: memory
    annotations:
      summary: "🧠 Alto uso de memoria RAM"
      description: "La instancia {{ $labels.instance }} está usando {{ $value | humanize }}% de RAM"

  - alert: MemoriaCritica
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 95
    for: 2m
    labels:
      severity: critical
      component: memory
    annotations:
      summary: "🔴 CRÍTICO: Memoria RAM agotada"
      description: "La instancia {{ $labels.instance }} tiene memoria RAM crítica: {{ $value | humanize }}%"

  # === ALERTAS DE DISCO ===
  - alert: DiscoLleno
    expr: (1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100 > 85
    for: 5m
    labels:
      severity: warning
      component: disk
    annotations:
      summary: "💾 Espacio en disco bajo"
      description: "El disco en {{ $labels.instance }} está al {{ $value | humanize }}% de capacidad"

  - alert: DiscoCritico
    expr: (1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100 > 95
    for: 2m
    labels:
      severity: critical
      component: disk
    annotations:
      summary: "🆘 CRÍTICO: Disco casi lleno"
      description: "El disco en {{ $labels.instance }} está al {{ $value | humanize }}% - ¡Espacio crítico!"

  # === ALERTAS DE RED ===
  - alert: AltaRedSubida
    expr: rate(node_network_transmit_bytes_total{device!="lo"}[5m]) > 100000000  # 100MB/s
    for: 10m
    labels:
      severity: warning
      component: network
    annotations:
      summary: "📤 Alto tráfico de subida"
      description: "Tráfico de subida elevado en {{ $labels.instance }}: {{ $value | humanize1024 }}B/s"

  - alert: AltaRedBajada
    expr: rate(node_network_receive_bytes_total{device!="lo"}[5m]) > 100000000  # 100MB/s
    for: 10m
    labels:
      severity: warning
      component: network
    annotations:
      summary: "📥 Alto tráfico de bajada"
      description: "Tráfico de bajada elevado en {{ $labels.instance }}: {{ $value | humanize1024 }}B/s"

  # === ALERTAS DE DISPONIBILIDAD ===
  - alert: InstanciaNoDisponible
    expr: up == 0
    for: 1m
    labels:
      severity: critical
      component: availability
    annotations:
      summary: "🔌 Servidor no disponible"
      description: "El job '{{ $labels.job }}' en la instancia {{ $labels.instance }} no está respondiendo"

  - alert: ExporterCaido
    expr: up{job!="prometheus"} == 0
    for: 3m
    labels:
      severity: warning
      component: monitoring
    annotations:
      summary: "📊 Exporter de métricas caído"
      description: "El exporter '{{ $labels.job }}' no está enviando métricas desde hace 3 minutos"

  # === ALERTAS DE I/O DISCO ===
  - alert: AltaIODisco
    expr: rate(node_disk_read_bytes_total[5m]) + rate(node_disk_written_bytes_total[5m]) > 50000000  # 50MB/s
    for: 15m
    labels:
      severity: warning
      component: disk_io
    annotations:
      summary: "💿 Alto I/O de disco"
      description: "I/O de disco elevado en {{ $labels.instance }}: {{ $value | humanize1024 }}B/s"

# === ALERTAS ESPECÍFICAS PARA WINDOWS ===
- name: AlertasWindows
  rules:
  - alert: AltaCargaCPUWindows
    expr: 100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[2m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
      component: cpu
      platform: windows
    annotations:
      summary: "🚨 Alta carga de CPU en Windows"
      description: "El servidor Windows {{ $labels.instance }} supera 80% de CPU: {{ $value | humanize }}%"

  - alert: AltaMemoriaWindows
    expr: (1 - (windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes)) * 100 > 85
    for: 5m
    labels:
      severity: warning
      component: memory
      platform: windows
    annotations:
      summary: "🧠 Alta memoria RAM en Windows"
      description: "El servidor Windows {{ $labels.instance }} usa {{ $value | humanize }}% de RAM"

  - alert: DiscoWindowsLleno
    expr: (1 - (windows_logical_disk_free_bytes{volume="C:"} / windows_logical_disk_size_bytes{volume="C:"})) * 100 > 85
    for: 5m
    labels:
      severity: warning
      component: disk
      platform: windows
    annotations:
      summary: "💾 Disco C: lleno en Windows"
      description: "El disco C: en {{ $labels.instance }} está al {{ $value | humanize }}%"

# === ALERTAS ESPECÍFICAS PARA CLOUD ===
- name: AlertasCloud
  rules:
  - alert: CreditsAWSBajos
    expr: increase(aws_billing_estimated_charges_total[24h]) > 10
    for: 1h
    labels:
      severity: warning
      component: billing
      platform: aws
    annotations:
      summary: "💰 Gastos AWS elevados"
      description: "Los gastos de AWS han aumentado: ${{ $value | humanize }} en 24h"

  - alert: RateLimitCloud
    expr: increase(node_network_receive_drop_total[5m]) > 100
    for: 5m
    labels:
      severity: warning
      component: network
      platform: cloud
    annotations:
      summary: "⚠️ Posible rate limiting"
      description: "Paquetes dropeados en {{ $labels.instance }}: {{ $value | humanize }}"

# === GRUPO DE ALERTAS PERSONALIZABLES ===
- name: AlertasPersonalizadas
  rules:
  # Agrega aquí tus alertas personalizadas
  # Ejemplo:
  # - alert: MiAlertaCustom
  #   expr: mi_metrica > 100
  #   for: 5m
  #   labels:
  #     severity: info
  #   annotations:
  #     summary: "Mi alerta personalizada"
  #     description: "Descripción de mi alerta"

# === ALERTAS DE SEGURIDAD BÁSICAS ===
- name: AlertasSeguridad
  rules:
  - alert: ConexionesSospechosas
    expr: increase(node_netstat_Tcp_CurrEstab[5m]) > 500
    for: 2m
    labels:
      severity: warning
      component: security
    annotations:
      summary: "🔒 Muchas conexiones TCP"
      description: "Alto número de conexiones TCP en {{ $labels.instance }}: {{ $value | humanize }}"

  - alert: ProcesosSospechosos
    expr: node_procs_running > 300
    for: 10m
    labels:
      severity: info
      component: security
    annotations:
      summary: "⚡ Muchos procesos ejecutándose"
      description: "Número elevado de procesos en {{ $labels.instance }}: {{ $value | humanize }}"