global: 
  scrape_interval: 15s 
  evaluation_interval: 15s 
 
rule_files: 
  - "alert.rules.yml" 
 
scrape_configs: 
  - job_name: "prometheus" 
    static_configs: 
      - targets: ["localhost:9090"] 
 
  - job_name: "local_windows" 
    static_configs: 
      - targets: ["host.docker.internal:9182"] 
 
  - job_name: "aws_ec2" 
    static_configs: 
      - targets: ["34.201.94.176:9100"] 
    scrape_interval: 30s 
 
