global: 
  scrape_interval: 15s 
  evaluation_interval: 15s 
 
rule_files: 
  - "alert.rules.yml" 
 
alerting: 
  alertmanagers: 
    - static_configs: 
        - targets: [] 
 
scrape_configs: 
  - job_name: "prometheus" 
    static_configs: 
      - targets: ["localhost:9090"] 
 
  - job_name: "windows_exporter" 
    static_configs: 
      - targets: ["host.docker.internal:9182"] 
