# Configuración Simplificada OptiMon
# Solo completa las credenciales de tu proveedor de nube

# ===========================================
# AWS - Solo completar estos campos
# ===========================================
aws:
  # Credenciales AWS (obligatorio)
  access_key_id: "AKIAVUQSPT6FA5HCVAZD"
  secret_access_key: "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"
  region: "us-east-1"  # Tu región preferida
  
  # OPCIONAL: Filtros avanzados (déjalos en blanco para detectar todo)
  filters:
    # Solo VMs con estos tags (opcional)
    include_tags: []
    # Ejemplo: ["Environment=production", "Monitor=true"]
    
    # Excluir tipos de instancia (opcional)
    exclude_types: ["t2.nano", "t2.micro"]

# ===========================================
# AZURE - Solo completar estos campos  
# ===========================================
azure:
  # Credenciales Azure (obligatorio)
  subscription_id: "fc65bab0-b9c6-4f34-b946-a69346fba01b"
  tenant_id: "e9f230ae-5205-4a80-ab59-f049c16e1551"
  client_id: "2d7d6adc-3140-4e60-938e-10ec3928c4cd"
  client_secret: "Vfz8Q~bSCEKDpAWT.TEH_gS9zkj7ucYGwS_cratl"
  
  # OPCIONAL: Filtros avanzados (déjalos en blanco para detectar todo)
  filters:
    # Solo estos grupos de recursos (opcional)
    resource_groups: []
    # Ejemplo: ["rg-production", "rg-staging"]
    
    # Solo estas regiones (opcional)
    regions: []
    # Ejemplo: ["East US", "West US 2"]

# ===========================================
# CONFIGURACIÓN AUTOMÁTICA
# El sistema detectará automáticamente:
# - Usuarios SSH apropiados por tipo de OS
# - Claves SSH asociadas a las VMs
# - IPs públicas/privadas disponibles
# - Puertos SSH estándar
# ===========================================

# OPCIONAL: Configuración de red local para servidores físicos
physical_servers:
  # Red local a escanear (opcional)
  network_scan:
    enabled: false
    subnet: "192.168.1.0/24"  # Tu red local
    ssh_users: ["admin", "ubuntu", "centos"]  # Usuarios comunes a probar
    
  # Servidores específicos (opcional)
  manual_servers: []
  # Ejemplo:
  # - ip: "192.168.1.100"
  #   name: "servidor-local"