# Archivo de ejemplo para credenciales
# Copia este archivo y personalízalo según tu proveedor de nube

# ===========================================
# CONFIGURACIÓN AWS
# ===========================================
aws:
  # Credenciales de acceso
  access_key_id: "TU_AWS_ACCESS_KEY_ID"
  secret_access_key: "TU_AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"  # Cambia por tu región preferida
  
  # Configuración de instancias
  monitoring:
    # Filtros para encontrar instancias (opcional)
    instance_filters:
      - Name: "tag:Environment"
        Values: ["production", "staging"]
      - Name: "instance-state-name"
        Values: ["running"]
    
    # Tags para identificar instancias a monitorear
    include_tags:
      - "monitoring=true"
      - "Environment=production"
    
    # Tipos de instancia a excluir del monitoreo
    exclude_instance_types:
      - "t2.nano"
      - "t2.micro"
  
  # Configuración SSH para acceso a instancias
  ssh:
    default_user: "ec2-user"  # Usuario por defecto para Amazon Linux
    key_file: "path/to/your/private-key.pem"
    port: 22
    
    # Usuarios específicos por tipo de OS
    users_by_os:
      ubuntu: "ubuntu"
      centos: "centos"
      rhel: "ec2-user"
      suse: "ec2-user"

# ===========================================
# CONFIGURACIÓN AZURE
# ===========================================
azure:
  # Credenciales de acceso
  subscription_id: "TU_AZURE_SUBSCRIPTION_ID"
  tenant_id: "TU_AZURE_TENANT_ID"
  client_id: "TU_AZURE_CLIENT_ID"
  client_secret: "TU_AZURE_CLIENT_SECRET"
  
  # Configuración de recursos
  monitoring:
    # Grupos de recursos a monitorear
    resource_groups:
      - "rg-production"
      - "rg-staging"
    
    # Regiones a incluir
    regions:
      - "East US"
      - "West US 2"
    
    # Tags para identificar VMs a monitorear
    include_tags:
      monitoring: "enabled"
      environment: "production"
    
    # Tipos de VM a excluir
    exclude_vm_sizes:
      - "Standard_B1ls"
      - "Standard_B1s"
  
  # Configuración SSH para acceso a VMs
  ssh:
    default_user: "azureuser"
    key_file: "path/to/your/private-key"
    port: 22
    
    # Credenciales alternativas
    users_by_os:
      linux: "azureuser"
      windows: "adminuser"  # Para WinRM

# ===========================================
# CONFIGURACIÓN SERVIDORES FÍSICOS
# ===========================================
physical_servers:
  # Lista de servidores físicos a monitorear
  servers:
    - name: "servidor-web-01"
      ip: "192.168.1.100"
      user: "monitoring"
      auth_method: "password"  # o "key"
      password: "tu_password"  # si usas password
      key_file: "path/to/key"  # si usas key
      port: 22
      os: "linux"  # linux o windows
      
    - name: "servidor-db-01"
      ip: "192.168.1.101"
      user: "admin"
      auth_method: "key"
      key_file: "/path/to/db-server-key.pem"
      port: 22
      os: "linux"
  
  # Configuración por defecto para servidores
  defaults:
    user: "monitoring"
    port: 22
    auth_method: "key"
    os: "linux"

# ===========================================
# CONFIGURACIÓN GENERAL
# ===========================================
general:
  # Configuración de Node Exporter
  node_exporter:
    version: "1.6.1"
    port: 9100
    install_path: "/opt/node_exporter"
    service_user: "node_exporter"
  
  # Configuración de monitoreo
  monitoring:
    # Intervalo de scraping en segundos
    scrape_interval: 15
    
    # Timeout para conexiones
    scrape_timeout: 10
    
    # Retención de métricas
    retention_time: "30d"
    
    # Alertas
    alerts:
      cpu_threshold: 80      # % CPU
      memory_threshold: 90   # % Memoria
      disk_threshold: 85     # % Disco
      
  # Configuración de red
  network:
    # Puertos utilizados por el sistema
    prometheus_port: 9090
    grafana_port: 3000
    alertmanager_port: 9093
    
    # Timeouts de conexión
    connection_timeout: 30
    ssh_timeout: 10

# ===========================================
# CONFIGURACIÓN DE NOTIFICACIONES
# ===========================================
notifications:
  # Email
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "tu_email@gmail.com"
    password: "tu_app_password"
    from_address: "monitoring@tuempresa.com"
    to_addresses:
      - "admin@tuempresa.com"
      - "devops@tuempresa.com"
  
  # Slack
  slack:
    enabled: false
    webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
    channel: "#monitoring"
    username: "OptiMon"
  
  # Microsoft Teams
  teams:
    enabled: false
    webhook_url: "https://your-tenant.webhook.office.com/webhookb2/..."

# ===========================================
# CONFIGURACIÓN DE LOGGING
# ===========================================
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Archivos de log
  files:
    main: "logs/optimon.log"
    errors: "logs/errors.log"
    access: "logs/access.log"
  
  # Rotación de logs
  rotation:
    max_size: "10MB"
    backup_count: 5