"""
OptiMon - Motor de Replicación de Infraestructura
Genera código Infrastructure as Code basado en VMs descubiertas
Autor: OptiMon Team
Versión: 3.1.0-IaC-REPLICATION
"""

import json
import os
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any

# Configurar logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class InfrastructureReplicationEngine:
    """Motor de replicación de infraestructura basado en VMs escaneadas"""
    
    def __init__(self):
        self.output_dir = Path("generated_infrastructure")
        self.output_dir.mkdir(exist_ok=True)
        
    def generate_terraform_aws(self, instances: List[Dict]) -> Dict[str, str]:
        """Generar Terraform para AWS basado en instancias descubiertas"""
        
        # Filtrar solo instancias AWS
        aws_instances = [inst for inst in instances if inst.get('provider') == 'aws']
        
        if not aws_instances:
            return {'error': 'No se encontraron instancias AWS para replicar'}
        
        # Generar código Terraform
        terraform_code = self._generate_aws_terraform_code(aws_instances)
        variables_code = self._generate_aws_variables()
        outputs_code = self._generate_aws_outputs(aws_instances)
        
        # Crear archivos
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        project_name = f"aws_replica_{timestamp}"
        project_dir = self.output_dir / project_name
        project_dir.mkdir(exist_ok=True)
        
        files = {
            'main.tf': terraform_code,
            'variables.tf': variables_code,
            'outputs.tf': outputs_code,
            'terraform.tfvars.example': self._generate_aws_tfvars_example(),
            'README.md': self._generate_aws_readme(aws_instances, project_name)
        }
        
        # Escribir archivos
        for filename, content in files.items():
            file_path = project_dir / filename
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
        
        return {
            'success': True,
            'project_name': project_name,
            'project_path': str(project_dir),
            'files_created': list(files.keys()),
            'instances_replicated': len(aws_instances),
            'download_url': f'/api/infrastructure/download/{project_name}'
        }
    
    def generate_terraform_azure(self, instances: List[Dict]) -> Dict[str, str]:
        """Generar Terraform para Azure basado en instancias descubiertas"""
        
        # Filtrar solo instancias Azure
        azure_instances = [inst for inst in instances if inst.get('provider') == 'azure']
        
        if not azure_instances:
            return {'error': 'No se encontraron instancias Azure para replicar'}
        
        # Generar código Terraform
        terraform_code = self._generate_azure_terraform_code(azure_instances)
        variables_code = self._generate_azure_variables()
        outputs_code = self._generate_azure_outputs(azure_instances)
        
        # Crear archivos
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        project_name = f"azure_replica_{timestamp}"
        project_dir = self.output_dir / project_name
        project_dir.mkdir(exist_ok=True)
        
        files = {
            'main.tf': terraform_code,
            'variables.tf': variables_code,
            'outputs.tf': outputs_code,
            'terraform.tfvars.example': self._generate_azure_tfvars_example(),
            'README.md': self._generate_azure_readme(azure_instances, project_name)
        }
        
        # Escribir archivos
        for filename, content in files.items():
            file_path = project_dir / filename
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
        
        return {
            'success': True,
            'project_name': project_name,
            'project_path': str(project_dir),
            'files_created': list(files.keys()),
            'instances_replicated': len(azure_instances),
            'download_url': f'/api/infrastructure/download/{project_name}'
        }
    
    def _generate_aws_terraform_code(self, instances: List[Dict]) -> str:
        """Generar código Terraform principal para AWS"""
        
        code = '''# Terraform configuration for AWS infrastructure replication
# Generated by OptiMon Infrastructure Replication Engine
# Date: {date}

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

# AWS Provider configuration
provider "aws" {{
  region     = var.aws_region
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
}}

# Data sources
data "aws_availability_zones" "available" {{
  state = "available"
}}

data "aws_ami" "ubuntu" {{
  most_recent = true
  owners      = ["099720109477"] # Canonical
  
  filter {{
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-20.04-lts-amd64-server-*"]
  }}
}}

# VPC and networking (if needed)
resource "aws_vpc" "replicated_vpc" {{
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true
  
  tags = {{
    Name = "OptiMon-Replicated-VPC"
    CreatedBy = "OptiMon-IaC-Replication"
  }}
}}

resource "aws_internet_gateway" "replicated_igw" {{
  vpc_id = aws_vpc.replicated_vpc.id
  
  tags = {{
    Name = "OptiMon-Replicated-IGW"
  }}
}}

resource "aws_subnet" "replicated_subnet" {{
  vpc_id                  = aws_vpc.replicated_vpc.id
  cidr_block              = var.subnet_cidr
  availability_zone       = data.aws_availability_zones.available.names[0]
  map_public_ip_on_launch = true
  
  tags = {{
    Name = "OptiMon-Replicated-Subnet"
  }}
}}

resource "aws_route_table" "replicated_rt" {{
  vpc_id = aws_vpc.replicated_vpc.id
  
  route {{
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.replicated_igw.id
  }}
  
  tags = {{
    Name = "OptiMon-Replicated-RT"
  }}
}}

resource "aws_route_table_association" "replicated_rta" {{
  subnet_id      = aws_subnet.replicated_subnet.id
  route_table_id = aws_route_table.replicated_rt.id
}}

# Security Group
resource "aws_security_group" "replicated_sg" {{
  name        = "optimon-replicated-sg"
  description = "Security group for replicated instances"
  vpc_id      = aws_vpc.replicated_vpc.id
  
  # SSH access
  ingress {{
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}
  
  # Node Exporter
  ingress {{
    from_port   = 9100
    to_port     = 9100
    protocol    = "tcp"
    cidr_blocks = [var.vpc_cidr]
  }}
  
  # HTTP/HTTPS
  ingress {{
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}
  
  ingress {{
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}
  
  # All outbound traffic
  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}
  
  tags = {{
    Name = "OptiMon-Replicated-SG"
  }}
}}

'''.format(date=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        
        # Agregar instancias
        for i, instance in enumerate(instances):
            instance_name = instance.get('name', f"instance-{i+1}").replace(' ', '-').lower()
            instance_type = instance.get('type', 't2.micro')
            
            code += f'''
# Replicated EC2 Instance: {instance.get('name', 'N/A')}
# Original ID: {instance.get('id', 'N/A')}
# Original Type: {instance_type}
resource "aws_instance" "replicated_{instance_name.replace('-', '_')}_{i+1}" {{
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "{instance_type}"
  subnet_id              = aws_subnet.replicated_subnet.id
  vpc_security_group_ids = [aws_security_group.replicated_sg.id]
  key_name              = var.key_pair_name
  
  # User data para instalar Node Exporter
  user_data = base64encode(templatefile("${{path.module}}/user_data.sh", {{}}))
  
  tags = {{
    Name = "OptiMon-Replica-{instance_name.title()}"
    OriginalId = "{instance.get('id', 'N/A')}"
    OriginalType = "{instance_type}"
    CreatedBy = "OptiMon-IaC-Replication"
    Environment = var.environment
  }}
}}
'''
        
        # Agregar script de user data
        user_data_script = '''
# Create user_data.sh file
cat > user_data.sh << 'EOF'
#!/bin/bash
# OptiMon Node Exporter Installation Script
# Auto-generated for replicated infrastructure

# Update system
apt-get update -y
apt-get upgrade -y

# Install Node Exporter
cd /tmp
wget https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
tar xvfz node_exporter-1.6.1.linux-amd64.tar.gz
sudo mv node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/
rm -rf node_exporter-1.6.1.linux-amd64*

# Create node_exporter user
sudo useradd --no-create-home --shell /bin/false node_exporter
sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter

# Create systemd service
sudo tee /etc/systemd/system/node_exporter.service > /dev/null <<EOL
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter --web.listen-address=:9100

[Install]
WantedBy=multi-user.target
EOL

# Start and enable Node Exporter
sudo systemctl daemon-reload
sudo systemctl start node_exporter
sudo systemctl enable node_exporter

# Install additional monitoring tools
apt-get install -y htop iotop nethogs

echo "Node Exporter installation completed!"
EOF
'''
        
        return code
    
    def _generate_aws_variables(self) -> str:
        """Generar archivo variables.tf para AWS"""
        return '''# Variables for AWS infrastructure replication
# Generated by OptiMon Infrastructure Replication Engine

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "aws_access_key" {
  description = "AWS access key"
  type        = string
  sensitive   = true
}

variable "aws_secret_key" {
  description = "AWS secret key"
  type        = string
  sensitive   = true
}

variable "vpc_cidr" {
  description = "CIDR block for VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "subnet_cidr" {
  description = "CIDR block for subnet"
  type        = string
  default     = "10.0.1.0/24"
}

variable "key_pair_name" {
  description = "Name of AWS key pair for SSH access"
  type        = string
}

variable "environment" {
  description = "Environment tag"
  type        = string
  default     = "replica"
}
'''
    
    def _generate_aws_outputs(self, instances: List[Dict]) -> str:
        """Generar archivo outputs.tf para AWS"""
        
        outputs = '''# Outputs for AWS infrastructure replication
# Generated by OptiMon Infrastructure Replication Engine

output "vpc_id" {
  description = "ID of the VPC"
  value       = aws_vpc.replicated_vpc.id
}

output "subnet_id" {
  description = "ID of the subnet"
  value       = aws_subnet.replicated_subnet.id
}

output "security_group_id" {
  description = "ID of the security group"
  value       = aws_security_group.replicated_sg.id
}

'''
        
        for i, instance in enumerate(instances):
            instance_name = instance.get('name', f"instance-{i+1}").replace(' ', '-').lower()
            outputs += f'''
output "instance_{instance_name.replace('-', '_')}_{i+1}_id" {{
  description = "ID of replicated instance {instance.get('name', 'N/A')}"
  value       = aws_instance.replicated_{instance_name.replace('-', '_')}_{i+1}.id
}}

output "instance_{instance_name.replace('-', '_')}_{i+1}_public_ip" {{
  description = "Public IP of replicated instance {instance.get('name', 'N/A')}"
  value       = aws_instance.replicated_{instance_name.replace('-', '_')}_{i+1}.public_ip
}}

output "instance_{instance_name.replace('-', '_')}_{i+1}_private_ip" {{
  description = "Private IP of replicated instance {instance.get('name', 'N/A')}"
  value       = aws_instance.replicated_{instance_name.replace('-', '_')}_{i+1}.private_ip
}}
'''
        
        return outputs
    
    def _generate_aws_tfvars_example(self) -> str:
        """Generar archivo terraform.tfvars.example para AWS"""
        return '''# Example Terraform variables file for AWS
# Copy this file to terraform.tfvars and fill in your values

aws_region     = "us-east-1"
aws_access_key = "YOUR_AWS_ACCESS_KEY"
aws_secret_key = "YOUR_AWS_SECRET_KEY"
key_pair_name  = "your-key-pair-name"
environment    = "production"

# Network configuration
vpc_cidr    = "10.0.0.0/16"
subnet_cidr = "10.0.1.0/24"
'''
    
    def _generate_aws_readme(self, instances: List[Dict], project_name: str) -> str:
        """Generar README.md para AWS"""
        
        instances_info = ""
        for i, instance in enumerate(instances, 1):
            instances_info += f"{i}. **{instance.get('name', 'N/A')}**\n"
            instances_info += f"   - Original ID: `{instance.get('id', 'N/A')}`\n"
            instances_info += f"   - Instance Type: `{instance.get('type', 'N/A')}`\n"
            instances_info += f"   - Status: `{instance.get('status', 'N/A')}`\n"
            instances_info += f"   - Zone: `{instance.get('zone', 'N/A')}`\n\n"
        
        return f'''# AWS Infrastructure Replication Project
## Generated by OptiMon Infrastructure Replication Engine

**Project:** {project_name}  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Instances Replicated:** {len(instances)}

## Overview

This Terraform project replicates your existing AWS infrastructure based on instances discovered by OptiMon. The infrastructure includes:

- VPC with public subnet
- Internet Gateway and routing
- Security groups with monitoring access
- EC2 instances with Node Exporter pre-installed

## Replicated Instances

{instances_info}

## Prerequisites

1. **Terraform installed** (>= 1.0)
2. **AWS CLI configured** or credentials available
3. **SSH Key Pair** created in AWS

## Quick Start

1. **Copy variables file:**
   ```bash
   cp terraform.tfvars.example terraform.tfvars
   ```

2. **Edit terraform.tfvars with your values:**
   ```hcl
   aws_access_key = "your_access_key"
   aws_secret_key = "your_secret_key"
   key_pair_name  = "your-key-pair"
   aws_region     = "us-east-1"
   ```

3. **Initialize Terraform:**
   ```bash
   terraform init
   ```

4. **Plan deployment:**
   ```bash
   terraform plan
   ```

5. **Apply infrastructure:**
   ```bash
   terraform apply
   ```

## Monitoring Integration

All instances are pre-configured with:
- **Node Exporter** on port 9100
- **SSH access** for management
- **Security groups** allowing monitoring traffic

To integrate with OptiMon:
1. Copy the instance IPs from `terraform output`
2. Add them to OptiMon monitoring configuration
3. Update Prometheus targets

## Customization

You can modify:
- Instance types in `main.tf`
- Network configuration in variables
- Security group rules
- User data scripts

## Cleanup

To destroy the infrastructure:
```bash
terraform destroy
```

## Support

This infrastructure was generated by OptiMon v3.1.0. For support:
- Check OptiMon documentation
- Review Terraform logs
- Verify AWS permissions

---
*Generated by OptiMon Infrastructure Replication Engine*
'''
    
    def _generate_azure_terraform_code(self, instances: List[Dict]) -> str:
        """Generar código Terraform principal para Azure"""
        
        code = '''# Terraform configuration for Azure infrastructure replication
# Generated by OptiMon Infrastructure Replication Engine
# Date: {date}

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }}
  }}
}}

# Azure Provider configuration
provider "azurerm" {{
  features {{}}
  
  subscription_id = var.azure_subscription_id
  client_id       = var.azure_client_id
  client_secret   = var.azure_client_secret
  tenant_id       = var.azure_tenant_id
}}

# Resource Group
resource "azurerm_resource_group" "replicated_rg" {{
  name     = "rg-optimon-replicated"
  location = var.azure_location
  
  tags = {{
    CreatedBy = "OptiMon-IaC-Replication"
    Environment = var.environment
  }}
}}

# Virtual Network
resource "azurerm_virtual_network" "replicated_vnet" {{
  name                = "vnet-optimon-replicated"
  address_space       = [var.vnet_cidr]
  location            = azurerm_resource_group.replicated_rg.location
  resource_group_name = azurerm_resource_group.replicated_rg.name
  
  tags = {{
    CreatedBy = "OptiMon-IaC-Replication"
  }}
}}

# Subnet
resource "azurerm_subnet" "replicated_subnet" {{
  name                 = "subnet-optimon-replicated"
  resource_group_name  = azurerm_resource_group.replicated_rg.name
  virtual_network_name = azurerm_virtual_network.replicated_vnet.name
  address_prefixes     = [var.subnet_cidr]
}}

# Network Security Group
resource "azurerm_network_security_group" "replicated_nsg" {{
  name                = "nsg-optimon-replicated"
  location            = azurerm_resource_group.replicated_rg.location
  resource_group_name = azurerm_resource_group.replicated_rg.name
  
  # SSH access
  security_rule {{
    name                       = "SSH"
    priority                   = 1001
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }}
  
  # Node Exporter
  security_rule {{
    name                       = "NodeExporter"
    priority                   = 1002
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "9100"
    source_address_prefix      = var.vnet_cidr
    destination_address_prefix = "*"
  }}
  
  # HTTP
  security_rule {{
    name                       = "HTTP"
    priority                   = 1003
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "80"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }}
  
  # HTTPS
  security_rule {{
    name                       = "HTTPS"
    priority                   = 1004
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "443"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }}
  
  tags = {{
    CreatedBy = "OptiMon-IaC-Replication"
  }}
}}

'''.format(date=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        
        # Agregar instancias
        for i, instance in enumerate(instances):
            instance_name = instance.get('name', f"vm-{i+1}").replace(' ', '-').lower()
            vm_size = instance.get('type', 'Standard_B1s')
            
            code += f'''
# Replicated Azure VM: {instance.get('name', 'N/A')}
# Original ID: {instance.get('id', 'N/A')}
# Original Size: {vm_size}

# Public IP for {instance_name}
resource "azurerm_public_ip" "replicated_{instance_name.replace('-', '_')}_{i+1}_pip" {{
  name                = "pip-{instance_name}-{i+1}"
  resource_group_name = azurerm_resource_group.replicated_rg.name
  location            = azurerm_resource_group.replicated_rg.location
  allocation_method   = "Static"
  
  tags = {{
    CreatedBy = "OptiMon-IaC-Replication"
  }}
}}

# Network Interface for {instance_name}
resource "azurerm_network_interface" "replicated_{instance_name.replace('-', '_')}_{i+1}_nic" {{
  name                = "nic-{instance_name}-{i+1}"
  location            = azurerm_resource_group.replicated_rg.location
  resource_group_name = azurerm_resource_group.replicated_rg.name
  
  ip_configuration {{
    name                          = "internal"
    subnet_id                     = azurerm_subnet.replicated_subnet.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.replicated_{instance_name.replace('-', '_')}_{i+1}_pip.id
  }}
  
  tags = {{
    CreatedBy = "OptiMon-IaC-Replication"
  }}
}}

# Associate Network Security Group to Network Interface
resource "azurerm_network_interface_security_group_association" "replicated_{instance_name.replace('-', '_')}_{i+1}_nsg_assoc" {{
  network_interface_id      = azurerm_network_interface.replicated_{instance_name.replace('-', '_')}_{i+1}_nic.id
  network_security_group_id = azurerm_network_security_group.replicated_nsg.id
}}

# Virtual Machine for {instance_name}
resource "azurerm_linux_virtual_machine" "replicated_{instance_name.replace('-', '_')}_{i+1}" {{
  name                = "vm-{instance_name}-{i+1}"
  resource_group_name = azurerm_resource_group.replicated_rg.name
  location            = azurerm_resource_group.replicated_rg.location
  size                = "{vm_size}"
  admin_username      = var.admin_username
  
  disable_password_authentication = true
  
  network_interface_ids = [
    azurerm_network_interface.replicated_{instance_name.replace('-', '_')}_{i+1}_nic.id,
  ]
  
  admin_ssh_key {{
    username   = var.admin_username
    public_key = var.ssh_public_key
  }}
  
  os_disk {{
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }}
  
  source_image_reference {{
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-focal"
    sku       = "20_04-lts-gen2"
    version   = "latest"
  }}
  
  custom_data = base64encode(templatefile("${{path.module}}/cloud_init.yml", {{}}))
  
  tags = {{
    Name = "OptiMon-Replica-{instance_name.title()}"
    OriginalId = "{instance.get('id', 'N/A')}"
    OriginalSize = "{vm_size}"
    CreatedBy = "OptiMon-IaC-Replication"
    Environment = var.environment
  }}
}}
'''
        
        return code
    
    def _generate_azure_variables(self) -> str:
        """Generar archivo variables.tf para Azure"""
        return '''# Variables for Azure infrastructure replication
# Generated by OptiMon Infrastructure Replication Engine

variable "azure_subscription_id" {
  description = "Azure subscription ID"
  type        = string
  sensitive   = true
}

variable "azure_client_id" {
  description = "Azure client ID"
  type        = string
  sensitive   = true
}

variable "azure_client_secret" {
  description = "Azure client secret"
  type        = string
  sensitive   = true
}

variable "azure_tenant_id" {
  description = "Azure tenant ID"
  type        = string
  sensitive   = true
}

variable "azure_location" {
  description = "Azure location for resources"
  type        = string
  default     = "East US"
}

variable "vnet_cidr" {
  description = "CIDR block for Virtual Network"
  type        = string
  default     = "10.0.0.0/16"
}

variable "subnet_cidr" {
  description = "CIDR block for subnet"
  type        = string
  default     = "10.0.1.0/24"
}

variable "admin_username" {
  description = "Admin username for VMs"
  type        = string
  default     = "azureuser"
}

variable "ssh_public_key" {
  description = "SSH public key for VM access"
  type        = string
}

variable "environment" {
  description = "Environment tag"
  type        = string
  default     = "replica"
}
'''
    
    def _generate_azure_outputs(self, instances: List[Dict]) -> str:
        """Generar archivo outputs.tf para Azure"""
        
        outputs = '''# Outputs for Azure infrastructure replication
# Generated by OptiMon Infrastructure Replication Engine

output "resource_group_name" {
  description = "Name of the resource group"
  value       = azurerm_resource_group.replicated_rg.name
}

output "virtual_network_name" {
  description = "Name of the virtual network"
  value       = azurerm_virtual_network.replicated_vnet.name
}

output "subnet_name" {
  description = "Name of the subnet"
  value       = azurerm_subnet.replicated_subnet.name
}

output "network_security_group_name" {
  description = "Name of the network security group"
  value       = azurerm_network_security_group.replicated_nsg.name
}

'''
        
        for i, instance in enumerate(instances):
            instance_name = instance.get('name', f"vm-{i+1}").replace(' ', '-').lower()
            outputs += f'''
output "vm_{instance_name.replace('-', '_')}_{i+1}_public_ip" {{
  description = "Public IP of replicated VM {instance.get('name', 'N/A')}"
  value       = azurerm_public_ip.replicated_{instance_name.replace('-', '_')}_{i+1}_pip.ip_address
}}

output "vm_{instance_name.replace('-', '_')}_{i+1}_private_ip" {{
  description = "Private IP of replicated VM {instance.get('name', 'N/A')}"
  value       = azurerm_network_interface.replicated_{instance_name.replace('-', '_')}_{i+1}_nic.private_ip_address
}}

output "vm_{instance_name.replace('-', '_')}_{i+1}_name" {{
  description = "Name of replicated VM {instance.get('name', 'N/A')}"
  value       = azurerm_linux_virtual_machine.replicated_{instance_name.replace('-', '_')}_{i+1}.name
}}
'''
        
        return outputs
    
    def _generate_azure_tfvars_example(self) -> str:
        """Generar archivo terraform.tfvars.example para Azure"""
        return '''# Example Terraform variables file for Azure
# Copy this file to terraform.tfvars and fill in your values

azure_subscription_id = "your-subscription-id"
azure_client_id       = "your-client-id"
azure_client_secret   = "your-client-secret"
azure_tenant_id       = "your-tenant-id"
azure_location        = "East US"
admin_username        = "azureuser"
ssh_public_key        = "ssh-rsa AAAAB3NzaC1yc2E... your-public-key"
environment           = "production"

# Network configuration
vnet_cidr   = "10.0.0.0/16"
subnet_cidr = "10.0.1.0/24"
'''
    
    def _generate_azure_readme(self, instances: List[Dict], project_name: str) -> str:
        """Generar README.md para Azure"""
        
        instances_info = ""
        for i, instance in enumerate(instances, 1):
            instances_info += f"{i}. **{instance.get('name', 'N/A')}**\n"
            instances_info += f"   - Original ID: `{instance.get('id', 'N/A')}`\n"
            instances_info += f"   - VM Size: `{instance.get('type', 'N/A')}`\n"
            instances_info += f"   - Status: `{instance.get('status', 'N/A')}`\n\n"
        
        return f'''# Azure Infrastructure Replication Project
## Generated by OptiMon Infrastructure Replication Engine

**Project:** {project_name}  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**VMs Replicated:** {len(instances)}

## Overview

This Terraform project replicates your existing Azure infrastructure based on VMs discovered by OptiMon. The infrastructure includes:

- Resource Group
- Virtual Network with subnet
- Network Security Group with monitoring rules
- Public IPs and Network Interfaces
- Linux VMs with Node Exporter pre-installed

## Replicated Virtual Machines

{instances_info}

## Prerequisites

1. **Terraform installed** (>= 1.0)
2. **Azure CLI configured** or service principal created
3. **SSH Key Pair** generated

## Quick Start

1. **Copy variables file:**
   ```bash
   cp terraform.tfvars.example terraform.tfvars
   ```

2. **Edit terraform.tfvars with your values:**
   ```hcl
   azure_subscription_id = "your-subscription-id"
   azure_client_id       = "your-client-id"
   azure_client_secret   = "your-client-secret"
   azure_tenant_id       = "your-tenant-id"
   ssh_public_key        = "your-ssh-public-key"
   ```

3. **Generate SSH key if needed:**
   ```bash
   ssh-keygen -t rsa -b 4096 -f ~/.ssh/azure_key
   cat ~/.ssh/azure_key.pub  # Copy this to terraform.tfvars
   ```

4. **Initialize Terraform:**
   ```bash
   terraform init
   ```

5. **Plan deployment:**
   ```bash
   terraform plan
   ```

6. **Apply infrastructure:**
   ```bash
   terraform apply
   ```

## Monitoring Integration

All VMs are pre-configured with:
- **Node Exporter** on port 9100
- **SSH access** for management
- **Network Security Groups** allowing monitoring traffic

To integrate with OptiMon:
1. Copy the VM IPs from `terraform output`
2. Add them to OptiMon monitoring configuration
3. Update Prometheus targets

## Customization

You can modify:
- VM sizes in `main.tf`
- Network configuration in variables
- Security group rules
- Cloud-init scripts

## Cloud-Init Configuration

Create a `cloud_init.yml` file for VM initialization:
```yaml
#cloud-config
package_upgrade: true
packages:
  - htop
  - iotop
  - nethogs

write_files:
  - path: /tmp/install_node_exporter.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      cd /tmp
      wget https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
      tar xvfz node_exporter-1.6.1.linux-amd64.tar.gz
      sudo mv node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/
      sudo useradd --no-create-home --shell /bin/false node_exporter
      sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter
      
      sudo tee /etc/systemd/system/node_exporter.service > /dev/null <<EOL
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target
      
      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter --web.listen-address=:9100
      
      [Install]
      WantedBy=multi-user.target
      EOL
      
      sudo systemctl daemon-reload
      sudo systemctl start node_exporter
      sudo systemctl enable node_exporter

runcmd:
  - /tmp/install_node_exporter.sh
```

## Cleanup

To destroy the infrastructure:
```bash
terraform destroy
```

## Support

This infrastructure was generated by OptiMon v3.1.0. For support:
- Check OptiMon documentation
- Review Terraform logs
- Verify Azure permissions

---
*Generated by OptiMon Infrastructure Replication Engine*
'''

# Instancia global del motor
replication_engine = InfrastructureReplicationEngine()