# Terraform Variables for optimon-demo
# Generated by OptiMon on 2025-11-04 19:24:58

environment   = "dev"
project_name  = "optimon-demo"
aws_region    = "us-west-2"
key_pair_name = "my-key-pair"  # Replace with your key pair name
