# Variables for optimon-demo
# Generated by OptiMon on 2025-11-04 19:24:58

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}

variable "project_name" {
  description = "Project name"  
  type        = string
  default     = "optimon-demo"
}
