
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://optimon_prometheus:9090
  isDefault: true
  editable: false
  basicAuth: false
  uid: prometheus-optimon
  jsonData:
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.40.0
    timeInterval: 15s