global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'optimon'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/api/metrics'

  - job_name: 'windows_local'
    static_configs:
      - targets: ['host.docker.internal:9182']
    scrape_interval: 30s
    metrics_path: '/metrics'